// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Element interface {
	IsElement()
	GetPost() Post
}

type Post interface {
	IsPost()
	GetID() string
}

type Compact struct {
	Post Post `json:"post,omitempty"`
}

func (Compact) IsElement()         {}
func (this Compact) GetPost() Post { return this.Post }

type Full struct {
	Post Post `json:"post,omitempty"`
}

func (Full) IsElement()         {}
func (this Full) GetPost() Post { return this.Post }

type Query struct {
}

type SimplePost struct {
	ID string `json:"id"`
}

func (SimplePost) IsPost()            {}
func (this SimplePost) GetID() string { return this.ID }

func (SimplePost) IsEntity() {}
