// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Element interface {
	IsElement()
	GetPost() Post
}

type Post interface {
	IsPost()
	GetID() string
}

type CardPostCommunityRecommendation struct {
	Post Post `json:"post,omitempty"`
}

func (CardPostCommunityRecommendation) IsElement()         {}
func (this CardPostCommunityRecommendation) GetPost() Post { return this.Post }

type CompactPostCommunityRecommendation struct {
	Post Post `json:"post,omitempty"`
}

func (CompactPostCommunityRecommendation) IsElement()         {}
func (this CompactPostCommunityRecommendation) GetPost() Post { return this.Post }

type Query struct {
}

type SubredditPost struct {
	ID string `json:"id"`
}

func (SubredditPost) IsPost()            {}
func (this SubredditPost) GetID() string { return this.ID }

func (SubredditPost) IsEntity() {}
