// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post interface {
	IsPost()
	GetID() string
	GetMedia() *string
}

type Query struct {
}

type SimplePost struct {
	ID    string  `json:"id"`
	Media *string `json:"media,omitempty"`
}

func (SimplePost) IsPost()                {}
func (this SimplePost) GetID() string     { return this.ID }
func (this SimplePost) GetMedia() *string { return this.Media }

func (SimplePost) IsEntity() {}
