// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post interface {
	IsPost()
	GetID() string
	GetMedia() *string
}

type Query struct {
}

type SubredditPost struct {
	ID    string  `json:"id"`
	Media *string `json:"media,omitempty"`
}

func (SubredditPost) IsPost()                {}
func (this SubredditPost) GetID() string     { return this.ID }
func (this SubredditPost) GetMedia() *string { return this.Media }

func (SubredditPost) IsEntity() {}
