package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	"main/graph/model"
)

// WatchFeed is the resolver for the watchFeed field.
func (r *queryResolver) WatchFeed(ctx context.Context) ([]model.Element, error) {
	panic(fmt.Errorf("not implemented: WatchFeed - watchFeed"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
